const TIMEZONE_COUNTRY: Record<string, string> = {
    'Europe/Madrid': 'ES',
    'Europe/Barcelona': 'ES',
    'Atlantic/Canary': 'ES',
    'Europe/London': 'GB',
    'Europe/Paris': 'FR',
    'Europe/Berlin': 'DE',
    'Europe/Rome': 'IT',
    'Europe/Amsterdam': 'NL',
    'Europe/Brussels': 'BE',
    'Europe/Lisbon': 'PT',
    'Atlantic/Azores': 'PT',
    'Europe/Vienna': 'AT',
    'Europe/Zurich': 'CH',
    'Europe/Stockholm': 'SE',
    'Europe/Oslo': 'NO',
    'Europe/Copenhagen': 'DK',
    'Europe/Helsinki': 'FI',
    'Europe/Warsaw': 'PL',
    'Europe/Prague': 'CZ',
    'Europe/Athens': 'GR',
    'Europe/Dublin': 'IE',
    'Europe/Bucharest': 'RO',
    'Europe/Budapest': 'HU',
    'Europe/Moscow': 'RU',
    'Europe/Istanbul': 'TR',
    'America/New_York': 'US',
    'America/Chicago': 'US',
    'America/Denver': 'US',
    'America/Los_Angeles': 'US',
    'America/Phoenix': 'US',
    'America/Anchorage': 'US',
    'Pacific/Honolulu': 'US',
    'America/Toronto': 'CA',
    'America/Vancouver': 'CA',
    'America/Mexico_City': 'MX',
    'America/Guatemala': 'GT',
    'America/Havana': 'CU',
    'America/Panama': 'PA',
    'America/Costa_Rica': 'CR',
    'America/Santo_Domingo': 'DO',
    'America/Bogota': 'CO',
    'America/Lima': 'PE',
    'America/Santiago': 'CL',
    'America/Buenos_Aires': 'AR',
    'America/Argentina/Buenos_Aires': 'AR',
    'America/Sao_Paulo': 'BR',
    'America/Caracas': 'VE',
    'America/Montevideo': 'UY',
    'America/Asuncion': 'PY',
    'America/La_Paz': 'BO',
    'America/Guayaquil': 'EC',
    'Asia/Tokyo': 'JP',
    'Asia/Seoul': 'KR',
    'Asia/Shanghai': 'CN',
    'Asia/Hong_Kong': 'HK',
    'Asia/Singapore': 'SG',
    'Asia/Bangkok': 'TH',
    'Asia/Dubai': 'AE',
    'Asia/Kolkata': 'IN',
    'Asia/Karachi': 'PK',
    'Asia/Manila': 'PH',
    'Asia/Jakarta': 'ID',
    'Australia/Sydney': 'AU',
    'Australia/Melbourne': 'AU',
    'Australia/Brisbane': 'AU',
    'Australia/Perth': 'AU',
    'Pacific/Auckland': 'NZ',
    'Pacific/Fiji': 'FJ',
    'Africa/Cairo': 'EG',
    'Africa/Johannesburg': 'ZA',
    'Africa/Lagos': 'NG',
    'Africa/Nairobi': 'KE',
    'Africa/Casablanca': 'MA',
};

/**
 * Converts an IANA timezone string to a "City, CC" display format.
 * Example: "Europe/Madrid" → "Madrid, ES"
 */
export function timezoneToLocation(timezone: string): string {
    if (!timezone || timezone === 'UTC') return timezone || '-';

    const city = timezone.split('/').pop()?.replace(/_/g, ' ') ?? timezone;
    const countryCode = TIMEZONE_COUNTRY[timezone];

    return countryCode ? `${city}, ${countryCode}` : city;
}
